spring:
  datasource:
    url: jdbc:mysql://${MYSQL_ADDR:192.168.153.131:3306}/${MYSQL_DATABASE:dk}?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false&zeroDateTimeBehavior=convertToNull&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: ${MYSQL_USERNAME:root}
    password: ${MYSQL_PASSWORD:hushoutao}
    driver-class-name: com.mysql.cj.jdbc.Driver